# Site settings
title: Frontend Web Developer London
# email: mail@frontendwebdeveloper.london
description: > # this means to ignore newlines until "baseurl:"
  This is the GitHub page for fwd.london. Here you will find blog posts and demos/ code experiments.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://frontendwebdeveloper.london" # the base hostname & protocol for your site
twitter_username: FWDlondon
github_username:  kiddhustle

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
